attack_dict = {
    "DELETE": ("Dark", 9999),
    "Judgment": ("All", 9999),
    "Seismic Toss": ("Fighting", 95),
    "Thunder": ("Electric", 110),
    "Flamethrower": ("Fire", 95),
    "Dragon Claw": ("Dragon", 80),
    "Hydropump": ("Water", 120),
    "Draco Meteor": ("Dragon", 130),
    "Earthquake": ("Ground", 100),
    "Roar of Time": ("Dragon", 150),
    "Shadow Ball": ("Ghost", 80),
    "Psystrike": ("Psychic", 100),
    "Blaze Kick": ("Fire", 85),
    "Sky Uppercut": ("Fighting", 85),
    "Stone Edge": ("Rock", 85),
    "Ice Beam": ("Ice", 95),
    "Rock Slide": ("Rock", 75),
    "Scratch": ("Normal", 40),
    "Aerial Ace": ("Flying", 90),
    "Thunder Punch": ("Electric", 75),
    "Ice Punch": ("Ice", 75),
    "Flare Blitz": ("Fire", 120),
    "Overheat": ("Fire", 130),
    "Solar Beam": ("Grass", 120),
    "Shadow Claw": ("Ghost", 70),
    "Hyper Beam": ("Normal", 150),
    "Iron Tail": ("Steel", 100),
    "Slash": ("Normal", 70),
}
