npc_attack_dict = [
    "Flamethrower",
    "Dragon Claw",
    "Hydropump",
    "Draco Meteor",
    "Earthquake",
    "Roar of Time",
    "Shadow Ball",
    "Psystrike",
    "Blaze Kick",
    "Sky Uppercut",
    "Stone Edge",
    "Ice Beam",
    "Rock Slide",
    "Scratch",
    "Aerial Ace",
    "Thunder Punch",
    "Ice Punch",
    "Flare Blitz",
    "Overheat",
    "Solar Beam",
    "Shadow Claw",
    "Hyper Beam",
    "Iron Tail",
    "Slash"
]
