import random

attack_dict = {
    "DELETE": ("Dark", 9999),
    "Judgment": ("All", 9999),
    "Seismic Toss": ("Fighting", 95),
    "Thunder": ("Electric", 110),
    "Thunderclap": ("Electric", 110),
    "Crunch": ("Dark", 80),
    "Stomping Tantrum": ("Ground", 75),
    "Magical Leaf": ("Grass", 80),
    "Flamethrower": ("Fire", 95),
    "Dragon Claw": ("Dragon", 80),
    "Hydropump": ("Water", 120),
    "Draco Meteor": ("Dragon", 130),
    "Moonblast": ("Fairy", 95),
    "Bitter Blade": ("Fire", 90),
    "Close Combat": ("Fighting", 120),
    "Phantom Force": ("Ghost", 90),
    "Outrage": ("Dragon", 120),
    "Aura Sphere": ("Fighting", 80),
    "Trump Card": ("Normal", random.randint(50, 175)),
    "Ominous Wind": ("Ghost", 75),
    "Sludge Bomb": ("Poison", 90),
    "Solar Blade": ("Grass", 125),
    "X-Scissor": ("Bug", 80),
    "Psychic Noise": ("Psychic", 75),
    "Expanding Force": ("Psychic", 80),
    "Bullet Punch": ("Steel", 95),
    "Flash Cannon": ("Steel", 80),
    "Earthquake": ("Ground", 100),
    "Roar of Time": ("Dragon", 150),
    "Shadow Ball": ("Ghost", 80),
    "Psystrike": ("Psychic", 100),
    "Blaze Kick": ("Fire", 85),
    "Sky Uppercut": ("Fighting", 85),
    "Stone Edge": ("Rock", 85),
    "Thunderbolt": ("Electric", 90),
    "Ice Beam": ("Ice", 95),
    "Rock Slide": ("Rock", 75),
    "Scratch": ("Normal", 40),
    "Aerial Ace": ("Flying", 90),
    "Thunder Punch": ("Electric", 75),
    "Psychic": ("Psychic", 90),
    "Surf": ("Water", 90),
    "Ice Punch": ("Ice", 75),
    "Flare Blitz": ("Fire", 120),
    "High Horsepower": ("Ground", 95),
    "Overheat": ("Fire", 130),
    "Solar Beam": ("Grass", 120),
    "Shadow Claw": ("Ghost", 70),
    "Rock Tomb": ("Rock", 70),
    "Hyper Beam": ("Normal", 150),
    "Iron Tail": ("Steel", 100),
    "Slash": ("Normal", 70),
}

