import random
from pokedex_player import Pokemon
# from attack_dict import attack_dict # ONLY USE WHEN CHECKING ATTACK DICT


Metagross = Pokemon("Metagross", None, "Steel", "Psychic",
                    80, 135, 130, 70, "Bullet Punch",
                    "Psychic", "Earthquake", "Sludge Bomb")

Escavalier = Pokemon("Escavalier", None, "Bug", "Steel",
                     10, 135, 105, 20, "X-Scissor",
                     "Iron Head", "Close Combat", "Drill Run")

Jolteon = Pokemon("Jolteon", None, "Electric", None,
                  65, 110, 95, 130, "Thunder",
                  "Shadow Ball", "Double Edge", "Dig")

Medicham = Pokemon("Medicham", None, "Fighting",
                   "Psychic", 60, 60, 75, 80,
                   "Close Combat", "Ice Punch", "Thunder Punch",
                   "Fire Punch")

Mismagius = Pokemon("Mismagius", None, "Ghost", None,
                    60, 105, 105, 105,"Shadow Ball",
                    "Psychic", "Thunder","Magical Leaf")

Clawitzer = Pokemon("Clawitzer", None, "Water", None,
                    71, 120, 89, 59, "Hydropump",
                    "Hyper Beam", "Aura Sphere", "Ice Beam")

Exeggutor_A = Pokemon("Alolan Exeggutor", None, "Grass",
                      "Dragon", 95, 125, 85, 45,
                      "Draco Meteor", "Leaf Storm", "Giga Impact",
                      "Earthquake")


Avalugg_H =Pokemon("Hisuian Avalugg", None, "Ice", "Rock",
                   95, 127, 184, 38, "Stone Edge",
                   "Earthquake", "Mountain Gale", "Giga Impact")

Blissey = Pokemon("Blissey", None, "Normal", None,
                  255, 75, 135, 55, "Hyper Beam",
                  "Shadow Ball", "Thunder", "Psychic")

Hariyama = Pokemon("Hariyama", None, "Fighting", None,
                   144, 120, 50, 50, "Close Combat",
                   "Surf", "Stone Edge", "Poison Jab")

Hoopa_U = Pokemon("Hoopa, Unbound", None, "Psychic", "Dark",
                  80, 170, 130, 80, "Focus Punch",
                  "Giga Impact", "Hyperspace Fury", "Future Sight")

# ALL POKEMON FROM THIS POINT WAS GENERATED BY CHATGPT

Abomasnow = Pokemon("Abomasnow", None, "Grass", "Ice",
                    90, 92, 85, 60, "Blizzard",
                    "Giga Drain", "Wood Hammer", "Ice Shard")

Ambipom = Pokemon("Ambipom", None, "Normal", None,
                  75, 100, 66, 115, "Fake Out",
                  "Double Hit", "U-turn", "Knock Off")

Amoonguss = Pokemon("Amoonguss", None, "Grass", "Poison",
                    114, 85, 80, 30, "Giga Drain",
                    "Sludge Wave", "Clear Smog", "Energy Ball")

Arcanine = Pokemon("Arcanine", None, "Fire", None,
                   90, 110, 80, 95, "Fire Blast",
                   "Extreme Speed", "Wild Charge", "Brick Break")

Appletun = Pokemon("Appletun", None, "Grass", "Dragon",
                   110, 100, 80, 30, "Grav Apple",
                   "Dragon Pulse", "Energy Ball", "Giga Drain")

Avalugg = Pokemon("Avalugg", None, "Ice", None,
                  95, 117, 184, 28, "Icicle Crash",
                  "Avalanche", "Body Press", "Bulldoze")


Azumarill = Pokemon("Azumarill", None, "Water", "Fairy",
                    100, 60, 80, 50, "Play Rough",
                    "Waterfall", "Aqua Jet", "Superpower")

Banette = Pokemon("Banette", None, "Ghost", None,
                  64, 115, 65, 65, "Shadow Punch",
                  "Shadow Sneak", "Knock Off", "Night Slash")

Barraskewda = Pokemon("Barraskewda", None, "Water", None,
                      61, 123, 60, 136, "Liquidation",
                      "Flip Turn", "Psychic Fangs", "Aqua Jet")

Bellibolt = Pokemon("Bellibolt", None, "Electric", None,
                    109, 103, 91, 45, "Discharge",
                    "Volt Switch", "Parabolic Charge", "Muddy Water")

Bombirdier = Pokemon("Bombirdier", None, "Flying", "Dark",
                     70, 103, 85, 82, "Brave Bird",
                     "Knock Off", "Dual Wingbeat", "Rock Throw")

Braviary = Pokemon("Braviary", None, "Normal", "Flying",
                   100, 123, 75, 80, "Brave Bird",
                   "Drill Peck", "U-turn", "Facade")

Braviary_H = Pokemon("Hisuian Braviary", None, "Psychic", "Flying",
                     110, 112, 70, 65, "Hurricane",
                     "Air Slash", "Psyshock", "Extrasensory")

Bruxish = Pokemon("Bruxish", None, "Water", "Psychic",
                  68, 105, 70, 92, "Psychic Fangs",
                  "Liquidation", "Aqua Jet", "Bite")

Basculegion = Pokemon("Basculegion", None, "Water", "Ghost",
                      120, 112, 75, 78, "Liquidation",
                      "Aqua Jet", "Shadow Sneak", "Poltergeist")


Cacturne = Pokemon("Cacturne", None, "Grass", "Dark",
                   70, 115, 60, 55, "Seed Bomb",
                   "Sucker Punch", "Drain Punch", "Night Slash")

Camerupt = Pokemon("Camerupt", None, "Fire", "Ground",
                   70, 105, 75, 40, "Earth Power",
                   "Lava Plume", "Ancient Power", "Eruption")

Carbink = Pokemon("Carbink", None, "Rock", "Fairy",
                  50, 50, 150, 50, "Power Gem",
                  "Dazzling Gleam", "Ancient Power", "Rock Throw")

Chandelure = Pokemon("Chandelure", None, "Ghost", "Fire",
                     60, 145, 90, 80, "Hex",
                     "Fire Blast", "Mystical Fire", "Energy Ball")

Crabominable = Pokemon("Crabominable", None, "Fighting", "Ice",
                       97, 132, 77, 43, "Ice Hammer",
                       "Hammer Arm", "Avalanche", "Dynamic Punch")

Decidueye = Pokemon("Decidueye", None, "Grass", "Ghost",
                    78, 107, 100, 70, "Leaf Blade",
                    "Brave Bird", "Shadow Sneak", "Energy Ball")

Decidueye_H = Pokemon("Hisuian Decidueye", None, "Grass", "Fighting",
                      88, 112, 95, 60, "Leaf Blade",
                      "Brave Bird", "Brick Break", "Drain Punch")

Drifblim = Pokemon("Drifblim", None, "Ghost", "Flying",
                   150, 90, 54, 80, "Hex",
                   "Air Slash", "Hurricane", "Shadow Sneak")

Dondozo = Pokemon("Dondozo", None, "Water", None,
                  150, 100, 115, 35, "Waterfall",
                  "Body Press", "Body Slam", "Bulldoze")

Espeon = Pokemon("Espeon", None, "Psychic", None,
                 65, 130, 95, 110, "Psyshock",
                 "Psybeam", "Dazzling Gleam", "Swift")

Umbreon = Pokemon("Umbreon", None, "Dark", None,
                  95, 65, 130, 65, "Foul Play",
                  "Assurance", "Snarl", "Bite")

Glaceon = Pokemon("Glaceon", None, "Ice", None,
                  65, 130, 110, 65, "Blizzard",
                  "Freeze-Dry", "Aurora Beam", "Icy Wind")

Leafeon = Pokemon("Leafeon", None, "Grass", None,
                  65, 110, 130, 95, "Leaf Blade",
                  "Quick Attack", "Bug Bite", "Razor Leaf")

Vaporeon = Pokemon("Vaporeon", None, "Water", None,
                   130, 110, 95, 65, "Hydro Pump",
                   "Scald", "Water Pulse", "Aurora Beam")

Electrode = Pokemon("Electrode", None, "Electric", None,
                    60, 80, 80, 150, "Discharge",
                    "Volt Switch", "Charge Beam", "Self-Destruct")

Espathra = Pokemon("Espathra", None, "Psychic", None,
                   95, 101, 60, 105, "Psyshock",
                   "Extrasensory", "Dazzling Gleam", "Air Slash")

Feraligatr = Pokemon("Feraligatr", None, "Water", None,
                     85, 105, 100, 78, "Waterfall",
                     "Ice Fang", "Superpower", "Aqua Jet")

Florges = Pokemon("Florges", None, "Fairy", None,
                  78, 112, 154, 75, "Dazzling Gleam",
                  "Energy Ball", "Draining Kiss", "Misty Explosion")

Floatzel = Pokemon("Floatzel", None, "Water", None,
                   85, 105, 55, 115, "Waterfall",
                   "Aqua Jet", "Flip Turn", "Ice Fang")


Gardevoir = Pokemon("Gardevoir", None, "Psychic", "Fairy",
                    68, 125, 115, 80, "Psyshock",
                    "Dazzling Gleam", "Energy Ball", "Mystical Fire")

Gallade = Pokemon("Gallade", None, "Psychic", "Fighting",
                  68, 125, 115, 80, "Close Combat",
                  "Psycho Cut", "Brick Break", "Night Slash")

Gyarados = Pokemon("Gyarados", None, "Water", "Flying",
                   95, 125, 100, 81, "Waterfall",
                   "Bounce", "Crunch", "Dragon Tail")

Haxorus = Pokemon("Haxorus", None, "Dragon", None,
                  76, 147, 90, 97, "Dragon Claw",
                  "Dragon Rush", "Night Slash", "Iron Tail")

Hatterene = Pokemon("Hatterene", None, "Psychic", "Fairy",
                    57, 136, 103, 29, "Dazzling Gleam",
                    "Psyshock", "Mystical Fire", "Draining Kiss")

Incineroar = Pokemon("Incineroar", None, "Fire", "Dark",
                     95, 115, 90, 60, "Darkest Lariat",
                     "Flare Blitz", "Brick Break", "Snarl")

Kilowattrel = Pokemon("Kilowattrel", None, "Electric", "Flying",
                      70, 105, 70, 125, "Hurricane",
                      "Volt Switch", "Discharge", "Air Slash")

Lanturn = Pokemon("Lanturn", None, "Water", "Electric",
                  125, 76, 76, 67, "Discharge",
                  "Scald", "Ice Beam", "Water Pulse")

Kommo_o = Pokemon("Kommo-o", None, "Dragon", "Fighting",
                  75, 110, 125, 85, "Dragon Claw",
                  "Brick Break", "Dragon Tail", "Body Press")

Krookodile = Pokemon("Krookodile", None, "Ground", "Dark",
                     95, 117, 92, 92, "Earthquake",
                     "Crunch", "Stone Edge", "Assurance")

Lucario = Pokemon("Lucario", None, "Fighting", "Steel",
                  70, 115, 90, 90, "Aura Sphere",
                  "Flash Cannon", "Brick Break", "Extreme Speed")

Lurantis = Pokemon("Lurantis", None, "Grass", None,
                   70, 105, 90, 45, "Leaf Blade",
                   "Solar Blade", "X-Scissor", "Night Slash")

Mabosstiff = Pokemon("Mabosstiff", None, "Dark", None,
                     80, 120, 90, 85, "Crunch",
                     "Assurance", "Psychic Fangs", "Play Rough")


Milotic = Pokemon("Milotic", None, "Water", None,
                  95, 100, 125, 81, "Scald",
                  "Ice Beam", "Hydro Pump", "Dragon Tail")


Magnezone = Pokemon("Magnezone", None, "Electric", "Steel",
                    70, 130, 115, 60, "Discharge",
                    "Flash Cannon", "Volt Switch", "Tri Attack")

Manectric = Pokemon("Manectric", None, "Electric", None,
                    70, 135, 80, 105, "Thunderbolt",
                    "Volt Switch", "Discharge", "Flamethrower")

Mimikyu = Pokemon("Mimikyu", None, "Ghost", "Fairy",
                  55, 90, 105, 96, "Play Rough",
                  "Shadow Sneak", "Drain Punch", "Night Slash")

Muk = Pokemon("Muk", None, "Poison", None,
              105, 105, 100, 50, "Gunk Shot",
              "Poison Jab", "Shadow Sneak", "Body Slam")

Muk_A = Pokemon("Alolan Muk", None, "Poison", "Dark",
                105, 105, 100, 50, "Gunk Shot",
                "Crunch", "Assurance", "Poison Fang")

Oricorio = Pokemon("Oricorio", None, "Flying", "Fire",
                   75, 98, 70, 93, "Air Slash",
                   "Revelation Dance", "Hurricane", "U-turn")

Overqwil = Pokemon("Overqwil", None, "Dark", "Poison",
                   85, 115, 95, 85, "Poison Jab",
                   "Crunch", "Aqua Jet", "Assurance")

Tauros_P_C = Pokemon("Paldean Tauros Combat", None, "Fighting", None,
                     75, 110, 105, 100, "Close Combat",
                     "Zen Headbutt", "Body Slam", "Wild Charge")

Tauros_P_B = Pokemon("Paldean Tauros Blaze", None, "Fighting", "Fire",
                     75, 110, 105, 100, "Close Combat",
                     "Flare Blitz", "Body Slam", "Wild Charge")

Tauros_P_A = Pokemon("Paldean Tauros Aqua", None, "Fighting", "Water",
                     75, 110, 105, 100, "Close Combat",
                     "Liquidation", "Body Slam", "Wild Charge")

Passimian = Pokemon("Passimian", None, "Fighting", None,
                    100, 120, 100, 80, "Close Combat",
                    "Rock Slide", "U-turn", "Earthquake")

Perrserker = Pokemon("Perrserker", None, "Steel", None,
                     70, 110, 100, 50, "Iron Head",
                     "Body Slam", "Assurance", "Metal Claw")

Porygon_Z = Pokemon("Porygon-Z", None, "Normal", None,
                    85, 135, 95, 90, "Tri Attack",
                    "Hyper Beam", "Psychic", "Shadow Ball")

Primarina = Pokemon("Primarina", None, "Water", "Fairy",
                    80, 126, 116, 60, "Hydro Pump",
                    "Moonblast", "Energy Ball", "Hyper Voice")

Pyroar = Pokemon("Pyroar", None, "Fire", "Normal",
                 86, 109, 90, 106, "Hyper Voice",
                 "Flamethrower", "Dark Pulse", "Hidden Power")

Quagsire = Pokemon("Quagsire", None, "Water", "Ground",
                   95, 85, 100, 35, "Earthquake",
                   "Waterfall", "Body Slam", "Ice Beam")

Rhyperior = Pokemon("Rhyperior", None, "Ground", "Rock",
                    115, 140, 130, 40, "Earthquake",
                    "Rock Wrecker", "Hammer Arm", "Megahorn")

Rotom = Pokemon("Rotom", None, "Electric", "Ghost",
                50, 95, 107, 91, "Thunderbolt",
                "Hex", "Volt Switch", "Dark Pulse")

Scrafty = Pokemon("Scrafty", None, "Dark", "Fighting",
                  65, 90, 115, 58, "Crunch",
                  "Brick Break", "Head Smash", "Assurance")

Sawsbuck = Pokemon("Sawsbuck", None, "Normal", "Grass",
                   80, 100, 95, 95, "Double-Edge",
                   "Horn Leech", "Body Slam", "Seed Bomb")

Sawk = Pokemon("Sawk", None, "Fighting", None,
               75, 125, 95, 85, "Close Combat",
               "Brick Break", "Poison Jab", "Ice Punch")

Skeledirge = Pokemon("Skeledirge", None, "Fire", "Ghost",
                     104, 110, 110, 66, "Shadow Ball",
                     "Flamethrower", "Hyper Voice", "Hex")

Slowbro = Pokemon("Slowbro", None, "Water", "Psychic",
                  95, 100, 110, 30, "Scald",
                  "Psyshock", "Ice Beam", "Body Slam")

Snorlax = Pokemon("Snorlax", None, "Normal", None,
                  160, 110, 110, 30, "Body Slam",
                  "Crunch", "Earthquake", "Ice Punch")

Spiritomb = Pokemon("Spiritomb", None, "Ghost", "Dark",
                    50, 92, 108, 35, "Dark Pulse",
                    "Hex", "Foul Play", "Assurance")

Staraptor = Pokemon("Staraptor", None, "Normal", "Flying",
                    85, 120, 80, 100, "Brave Bird",
                    "Close Combat", "Double-Edge", "U-turn")

Sneasler = Pokemon("Sneasler", None, "Fighting", "Poison",
                   80, 130, 80, 120, "Close Combat",
                   "Poison Jab", "Brick Break", "Night Slash")

Toxicroak = Pokemon("Toxicroak", None, "Poison", "Fighting",
                    83, 106, 90, 85, "Drain Punch",
                    "Gunk Shot", "Brick Break", "Sucker Punch")

Torterra = Pokemon("Torterra", None, "Grass", "Ground",
                   95, 109, 115, 56, "Earthquake",
                   "Seed Bomb", "Wood Hammer", "Body Slam")

Ursaluna = Pokemon("Ursaluna", None, "Ground", "Normal",
                   130, 140, 105, 50, "Earthquake",
                   "Facade", "Body Slam", "Headlong Rush")

Vileplume = Pokemon("Vileplume", None, "Grass", "Poison",
                    75, 110, 100, 50, "Sludge Wave",
                    "Energy Ball", "Giga Drain", "Petal Dance")

Vivillon = Pokemon("Vivillon", None, "Bug", "Flying",
                   80, 100, 75, 89, "Bug Buzz",
                   "Hurricane", "U-turn", "Energy Ball")

Whimsicott = Pokemon("Whimsicott", None, "Grass", "Fairy",
                     60, 95, 95, 116, "Energy Ball",
                     "Dazzling Gleam", "Giga Drain", "Moonblast")

Whiscash = Pokemon("Whiscash", None, "Water", "Ground",
                   110, 100, 90, 60, "Earthquake",
                   "Waterfall", "Stone Edge", "Body Slam")

Xatu = Pokemon("Xatu", None, "Psychic", "Flying",
               85, 95, 95, 95, "Psyshock",
               "Air Slash", "U-turn", "Dazzling Gleam")

Zoroark = Pokemon("Zoroark", None, "Dark", None,
                  60, 120, 80, 105, "Night Daze",
                  "Shadow Sneak", "Knock Off", "Dark Pulse")

Zoroark_H = Pokemon("Hisuian Zoroark", None, "Normal", "Ghost",
                    55, 125, 90, 110, "Hex",
                    "Shadow Sneak", "Body Slam", "Night Slash")

wild_poke = [Metagross, Escavalier, Jolteon, Medicham, Mismagius, Clawitzer,
             Exeggutor_A, Avalugg_H, Blissey, Hariyama, Hoopa_U,
             Abomasnow, Ambipom, Amoonguss, Arcanine, Appletun, Avalugg,
             Azumarill, Banette, Barraskewda, Bellibolt, Bombirdier, Braviary, Braviary_H,
             Bruxish, Basculegion, Cacturne, Camerupt, Carbink, Chandelure,
             Crabominable, Decidueye, Decidueye_H, Drifblim, Dondozo, Espeon, Umbreon,
             Glaceon, Leafeon, Vaporeon, Electrode, Espathra, Feraligatr, Florges, Floatzel,
             Gardevoir, Gallade, Gyarados, Haxorus, Hatterene, Incineroar, Kilowattrel,
             Lanturn, Kommo_o, Krookodile, Lucario, Lurantis, Mabosstiff,
             Milotic, Magnezone, Manectric, Mimikyu, Muk, Muk_A, Oricorio,
             Overqwil, Tauros_P_C, Tauros_P_B, Tauros_P_A, Passimian, Perrserker,
             Porygon_Z, Primarina, Pyroar, Quagsire, Rhyperior, Rotom, Scrafty, Sawsbuck,
             Sawk, Skeledirge, Slowbro, Snorlax, Spiritomb, Staraptor, Sneasler, Toxicroak,
             Torterra, Ursaluna, Vileplume, Vivillon, Whimsicott, Whiscash, Xatu,
             Zoroark, Zoroark_H
             ]

# for pokemon in wild_poke:  # THIS CODE IS FOR TESTING GENERATED POKEMON ATTACKS ARE IN THE ATTACK DICT
#         if pokemon.atk_1 not in attack_dict:
#             print(str(pokemon.atk_1))
#         if pokemon.atk_2 not in attack_dict:
#             print(str(pokemon.atk_2))
#         if pokemon.atk_3 not in attack_dict:
#             print(str(pokemon.atk_3))
#         if pokemon.atk_4 not in attack_dict:
#             print(str(pokemon.atk_4))

